; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23918.0 

	TITLE	c:\Users\varmaav\documents\visual studio 2015\Projects\Hypervisor\Hypervisor\entry.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?kernel_entry@@YAXXZ				; kernel_entry
EXTRN	_main:PROC
EXTRN	?InitializeConstructors@@YAXXZ:PROC		; InitializeConstructors
EXTRN	?Exit@@YAXXZ:PROC				; Exit
; Function compile flags: /Odtp
; File c:\users\varmaav\documents\visual studio 2015\projects\hypervisor\hypervisor\entry.cpp
_TEXT	SEGMENT
?kernel_entry@@YAXXZ PROC				; kernel_entry

; 13   : void __cdecl kernel_entry() {

	push	ebp
	mov	ebp, esp

; 14   : 
; 15   : #ifdef ARCH_X86
; 16   :     _asm {
; 17   :         cli

	cli

; 18   :         mov ax, 10h

	mov	ax, 16					; 00000010H

; 19   :         mov ds, ax

	mov	ds, ax

; 20   :         mov es, ax

	mov	es, ax

; 21   :         mov fs, ax

	mov	fs, ax

; 22   :         mov gs, ax

	mov	gs, ax

; 23   :         mov ss, ax

	mov	ss, ax

; 24   :         mov esp, 0x90000

	mov	esp, 589824				; 00090000H

; 25   :         mov ebp, esp

	mov	ebp, esp

; 26   :         push ebp

	push	ebp

; 27   :     }
; 28   : #endif
; 29   : 
; 30   :     InitializeConstructors();

	call	?InitializeConstructors@@YAXXZ		; InitializeConstructors

; 31   : 
; 32   :     main();

	call	_main

; 33   : 
; 34   :     Exit();

	call	?Exit@@YAXXZ				; Exit

; 35   : 
; 36   : #ifdef ARCH_X86
; 37   :     _asm cli

	cli
$LN4@kernel_ent:

; 38   : #endif // ARCH_X86
; 39   :     for (;;);

	jmp	SHORT $LN4@kernel_ent

; 40   : }

	pop	ebp
	ret	0
?kernel_entry@@YAXXZ ENDP				; kernel_entry
_TEXT	ENDS
END
